//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsfRbrPowerSteering.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RsfRbrPowerSteering.Model.ModelTexts", typeof(ModelTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not export cars: {0}.
        /// </summary>
        internal static string PersonalDataExportCarsErrorFormat {
            get {
                return ResourceManager.GetString("PersonalDataExportCarsErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import cars from &quot;{0}&quot;: {1}.
        /// </summary>
        internal static string PersonalDataImportCarsErrorFormat {
            get {
                return ResourceManager.GetString("PersonalDataImportCarsErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import file &quot;{0}&quot; does not exist..
        /// </summary>
        internal static string PersonalDataImportCarsNotFoundFormat {
            get {
                return ResourceManager.GetString("PersonalDataImportCarsNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The import file &quot;{0}&quot; contained no data..
        /// </summary>
        internal static string PersonalDataImportCarsNullFormat {
            get {
                return ResourceManager.GetString("PersonalDataImportCarsNullFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The personal data was not yet loaded..
        /// </summary>
        internal static string PersonalDataNotLoadedError {
            get {
                return ResourceManager.GetString("PersonalDataNotLoadedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not read car with ID {0}: {1}.
        /// </summary>
        internal static string PersonalDataReadCarErrorExceptionFormat {
            get {
                return ResourceManager.GetString("PersonalDataReadCarErrorExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car with ID {0} not found in RSF cache..
        /// </summary>
        internal static string PersonalDataReadCarErrorMissingInCacheFormat {
            get {
                return ResourceManager.GetString("PersonalDataReadCarErrorMissingInCacheFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car with ID {0} not found in &quot;{1}&quot;..
        /// </summary>
        internal static string PersonalDataReadCarErrorNotFoundFormat {
            get {
                return ResourceManager.GetString("PersonalDataReadCarErrorNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weight ratio must be greater than or equal to zero and less than or equal to one..
        /// </summary>
        internal static string WeightRatioRangeError {
            get {
                return ResourceManager.GetString("WeightRatioRangeError", resourceCulture);
            }
        }
    }
}
