//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RsfRbrPowerSteering.View {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ViewTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ViewTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RsfRbrPowerSteering.View.ViewTexts", typeof(ViewTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustments [%].
        /// </summary>
        public static string AdjustmentsLabel {
            get {
                return ResourceManager.GetString("AdjustmentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string CarLabel {
            get {
                return ResourceManager.GetString("CarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string CarPrimaryLabel {
            get {
                return ResourceManager.GetString("CarPrimaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string CarSecondaryLabel {
            get {
                return ResourceManager.GetString("CarSecondaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reload Cars.
        /// </summary>
        public static string CarsReloadButton {
            get {
                return ResourceManager.GetString("CarsReloadButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Clear.
        /// </summary>
        public static string ClearFfbSensButton {
            get {
                return ResourceManager.GetString("ClearFfbSensButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivetrain.
        /// </summary>
        public static string ColumnNameDrivetrain {
            get {
                return ResourceManager.GetString("ColumnNameDrivetrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFB Sens
        ///Gravel.
        /// </summary>
        public static string ColumnNameFfbSensCalculatedGravel {
            get {
                return ResourceManager.GetString("ColumnNameFfbSensCalculatedGravel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFB Sens
        ///Snow.
        /// </summary>
        public static string ColumnNameFfbSensCalculatedSnow {
            get {
                return ResourceManager.GetString("ColumnNameFfbSensCalculatedSnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFB Sens
        ///Tarmac.
        /// </summary>
        public static string ColumnNameFfbSensCalculatedTarmac {
            get {
                return ResourceManager.GetString("ColumnNameFfbSensCalculatedTarmac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steering
        ///Lock-to-lock
        ///Rotation [°].
        /// </summary>
        public static string ColumnNameLockToLockRotation {
            get {
                return ResourceManager.GetString("ColumnNameLockToLockRotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car.
        /// </summary>
        public static string ColumnNameName {
            get {
                return ResourceManager.GetString("ColumnNameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight [kg].
        /// </summary>
        public static string ColumnNameWeight {
            get {
                return ResourceManager.GetString("ColumnNameWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This utility is for Richard Burns Rally (RBR) as distributed by RallySimFan.hu (RSF). It allows to set the force-feedback (FFB) sensitivity for all cars that you have driven previously, based on the lock-to-lock rotation of the steering wheel and/or the vehicle weight. Additional scaling can be applied depending on drive-train and surface.
        ///Set the FFB sensitivity for each surface for two lock-to-lock rotations and/or weights, or select two cars that have personal settings (in the RSF launcher under &quot;My Car [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show or hide help. [F1].
        /// </summary>
        public static string DescriptionToggleButtonToolTip {
            get {
                return ResourceManager.GetString("DescriptionToggleButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AWD.
        /// </summary>
        public static string DrivetrainAwdLabel {
            get {
                return ResourceManager.GetString("DrivetrainAwdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FWD.
        /// </summary>
        public static string DrivetrainFwdLabel {
            get {
                return ResourceManager.GetString("DrivetrainFwdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drivetrain.
        /// </summary>
        public static string DrivetrainLabel {
            get {
                return ResourceManager.GetString("DrivetrainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RWD.
        /// </summary>
        public static string DrivetrainRwdLabel {
            get {
                return ResourceManager.GetString("DrivetrainRwdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a whole number..
        /// </summary>
        public static string EmptyValueError {
            get {
                return ResourceManager.GetString("EmptyValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steering Lock-to-Lock
        ///Rotation [°].
        /// </summary>
        public static string LockToLockRotationLabel {
            get {
                return ResourceManager.GetString("LockToLockRotationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following files could not be found:
        ///{1}
        ///
        ///Please make sure the working directory is the directory of your RallySimFans.hu Richard Burns Rally installation. The easiest way is to place the executable in this directory.
        ///
        ///Current directory: {0}.
        /// </summary>
        public static string MissingFilesError {
            get {
                return ResourceManager.GetString("MissingFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Update FFB Sensitivity.
        /// </summary>
        public static string PersonalSettingsApplyButton {
            get {
                return ResourceManager.GetString("PersonalSettingsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export.
        /// </summary>
        public static string PersonalSettingsExportButton {
            get {
                return ResourceManager.GetString("PersonalSettingsExportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string PersonalSettingsImportButton {
            get {
                return ResourceManager.GetString("PersonalSettingsImportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Car Settings.
        /// </summary>
        public static string PersonalSettingsLabel {
            get {
                return ResourceManager.GetString("PersonalSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No car selected..
        /// </summary>
        public static string PersonalSettingsTargetCarComboBoxText {
            get {
                return ResourceManager.GetString("PersonalSettingsTargetCarComboBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _All cars.
        /// </summary>
        public static string PersonalSettingsTargetCarNoneCheckBox {
            get {
                return ResourceManager.GetString("PersonalSettingsTargetCarNoneCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview of Personal Car Settings.
        /// </summary>
        public static string PreviewTitleLabel {
            get {
                return ResourceManager.GetString("PreviewTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset to Defaults.
        /// </summary>
        public static string ResetToDefaultsButton {
            get {
                return ResourceManager.GetString("ResetToDefaultsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Individual.
        /// </summary>
        public static string SetPrimarySurfaceNullButton {
            get {
                return ResourceManager.GetString("SetPrimarySurfaceNullButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravel.
        /// </summary>
        public static string SurfaceGravelLabel {
            get {
                return ResourceManager.GetString("SurfaceGravelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFB Sensitivity.
        /// </summary>
        public static string SurfaceLabel {
            get {
                return ResourceManager.GetString("SurfaceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snow.
        /// </summary>
        public static string SurfaceSnowLabel {
            get {
                return ResourceManager.GetString("SurfaceSnowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarmac.
        /// </summary>
        public static string SurfaceTarmaclLabel {
            get {
                return ResourceManager.GetString("SurfaceTarmaclLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected problem occurred: {0}.
        /// </summary>
        public static string UnexpectedExceptionErrorFormat {
            get {
                return ResourceManager.GetString("UnexpectedExceptionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight [kg].
        /// </summary>
        public static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSF RBR Power Steering.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
